name: Check Markdown lints

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: add markdownlint-cli
        run : |
          echo "install markdownlint-cli"
          yarn global add markdownlint-cli
      
      - name: run markdonwlint-cli
        run : |
          markdownlint **/*.md --disable MD013
